t(0.5)::party(democrat).
t(0.5)::party(republic).

t(_)::h_class:-party(democrat).
t(_)::h_class:-party(republic).

t(_)::handicapped:-party(democrat),h_class.
t(_)::water:-party(democrat),h_class.
t(_)::adoption:-party(democrat),h_class.
t(_)::physician:-party(democrat),h_class.
t(_)::immigration:-party(democrat),h_class.
t(_)::synfuels:-party(democrat),h_class.
t(_)::superfund:-party(democrat),h_class.
t(_)::education:-party(democrat),h_class.
t(_)::religious:-party(democrat),h_class.
t(_)::export:-party(democrat),h_class.
t(_)::crime:-party(democrat),h_class.
t(_)::anti:-party(democrat),h_class.
t(_)::duty:-party(democrat),h_class.
t(_)::aid:-party(democrat),h_class.
t(_)::mx:-party(democrat),h_class.
t(_)::el:-party(democrat),h_class.

t(_)::handicapped:-party(republic),h_class.
t(_)::water:-party(republic),h_class.
t(_)::adoption:-party(republic),h_class.
t(_)::physician:-party(republic),h_class.
t(_)::immigration:-party(republic),h_class.
t(_)::synfuels:-party(republic),h_class.
t(_)::superfund:-party(republic),h_class.
t(_)::education:-party(republic),h_class.
t(_)::religious:-party(republic),h_class.
t(_)::export:-party(republic),h_class.
t(_)::crime:-party(republic),h_class.
t(_)::anti:-party(republic),h_class.
t(_)::duty:-party(republic),h_class.
t(_)::aid:-party(republic),h_class.
t(_)::mx:-party(republic),h_class.
t(_)::el:-party(republic),h_class.
