evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(3),true).
evidence(persons(4),true).
evidence(lug_boot(big),true).
evidence(safety(med),true).
query(car(_))
good
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(3),true).
evidence(persons(4),true).
evidence(lug_boot(big),true).
evidence(safety(high),true).
query(car(_))
vgood
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(3),true).
evidence(persons(more),true).
evidence(lug_boot(small),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(3),true).
evidence(persons(more),true).
evidence(lug_boot(small),true).
evidence(safety(med),true).
query(car(_))
acc
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(3),true).
evidence(persons(more),true).
evidence(lug_boot(small),true).
evidence(safety(high),true).
query(car(_))
good
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(3),true).
evidence(persons(more),true).
evidence(lug_boot(med),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(3),true).
evidence(persons(more),true).
evidence(lug_boot(med),true).
evidence(safety(med),true).
query(car(_))
good
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(3),true).
evidence(persons(more),true).
evidence(lug_boot(med),true).
evidence(safety(high),true).
query(car(_))
vgood
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(3),true).
evidence(persons(more),true).
evidence(lug_boot(big),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(3),true).
evidence(persons(more),true).
evidence(lug_boot(big),true).
evidence(safety(med),true).
query(car(_))
good
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(3),true).
evidence(persons(more),true).
evidence(lug_boot(big),true).
evidence(safety(high),true).
query(car(_))
vgood
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(4),true).
evidence(persons(2),true).
evidence(lug_boot(small),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(4),true).
evidence(persons(2),true).
evidence(lug_boot(small),true).
evidence(safety(med),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(4),true).
evidence(persons(2),true).
evidence(lug_boot(small),true).
evidence(safety(high),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(4),true).
evidence(persons(2),true).
evidence(lug_boot(med),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(4),true).
evidence(persons(2),true).
evidence(lug_boot(med),true).
evidence(safety(med),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(4),true).
evidence(persons(2),true).
evidence(lug_boot(med),true).
evidence(safety(high),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(4),true).
evidence(persons(2),true).
evidence(lug_boot(big),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(4),true).
evidence(persons(2),true).
evidence(lug_boot(big),true).
evidence(safety(med),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(4),true).
evidence(persons(2),true).
evidence(lug_boot(big),true).
evidence(safety(high),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(4),true).
evidence(persons(4),true).
evidence(lug_boot(small),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(4),true).
evidence(persons(4),true).
evidence(lug_boot(small),true).
evidence(safety(med),true).
query(car(_))
acc
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(4),true).
evidence(persons(4),true).
evidence(lug_boot(small),true).
evidence(safety(high),true).
query(car(_))
good
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(4),true).
evidence(persons(4),true).
evidence(lug_boot(med),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(4),true).
evidence(persons(4),true).
evidence(lug_boot(med),true).
evidence(safety(med),true).
query(car(_))
good
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(4),true).
evidence(persons(4),true).
evidence(lug_boot(med),true).
evidence(safety(high),true).
query(car(_))
vgood
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(4),true).
evidence(persons(4),true).
evidence(lug_boot(big),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(4),true).
evidence(persons(4),true).
evidence(lug_boot(big),true).
evidence(safety(med),true).
query(car(_))
good
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(4),true).
evidence(persons(4),true).
evidence(lug_boot(big),true).
evidence(safety(high),true).
query(car(_))
vgood
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(4),true).
evidence(persons(more),true).
evidence(lug_boot(small),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(4),true).
evidence(persons(more),true).
evidence(lug_boot(small),true).
evidence(safety(med),true).
query(car(_))
acc
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(4),true).
evidence(persons(more),true).
evidence(lug_boot(small),true).
evidence(safety(high),true).
query(car(_))
good
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(4),true).
evidence(persons(more),true).
evidence(lug_boot(med),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(4),true).
evidence(persons(more),true).
evidence(lug_boot(med),true).
evidence(safety(med),true).
query(car(_))
good
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(4),true).
evidence(persons(more),true).
evidence(lug_boot(med),true).
evidence(safety(high),true).
query(car(_))
vgood
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(4),true).
evidence(persons(more),true).
evidence(lug_boot(big),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(4),true).
evidence(persons(more),true).
evidence(lug_boot(big),true).
evidence(safety(med),true).
query(car(_))
good
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(4),true).
evidence(persons(more),true).
evidence(lug_boot(big),true).
evidence(safety(high),true).
query(car(_))
vgood
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(more),true).
evidence(persons(2),true).
evidence(lug_boot(small),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(more),true).
evidence(persons(2),true).
evidence(lug_boot(small),true).
evidence(safety(med),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(more),true).
evidence(persons(2),true).
evidence(lug_boot(small),true).
evidence(safety(high),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(more),true).
evidence(persons(2),true).
evidence(lug_boot(med),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(more),true).
evidence(persons(2),true).
evidence(lug_boot(med),true).
evidence(safety(med),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(more),true).
evidence(persons(2),true).
evidence(lug_boot(med),true).
evidence(safety(high),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(more),true).
evidence(persons(2),true).
evidence(lug_boot(big),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(more),true).
evidence(persons(2),true).
evidence(lug_boot(big),true).
evidence(safety(med),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(more),true).
evidence(persons(2),true).
evidence(lug_boot(big),true).
evidence(safety(high),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(more),true).
evidence(persons(4),true).
evidence(lug_boot(small),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(more),true).
evidence(persons(4),true).
evidence(lug_boot(small),true).
evidence(safety(med),true).
query(car(_))
acc
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(more),true).
evidence(persons(4),true).
evidence(lug_boot(small),true).
evidence(safety(high),true).
query(car(_))
good
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(more),true).
evidence(persons(4),true).
evidence(lug_boot(med),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(more),true).
evidence(persons(4),true).
evidence(lug_boot(med),true).
evidence(safety(med),true).
query(car(_))
good
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(more),true).
evidence(persons(4),true).
evidence(lug_boot(med),true).
evidence(safety(high),true).
query(car(_))
vgood
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(more),true).
evidence(persons(4),true).
evidence(lug_boot(big),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(more),true).
evidence(persons(4),true).
evidence(lug_boot(big),true).
evidence(safety(med),true).
query(car(_))
good
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(more),true).
evidence(persons(4),true).
evidence(lug_boot(big),true).
evidence(safety(high),true).
query(car(_))
vgood
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(more),true).
evidence(persons(more),true).
evidence(lug_boot(small),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(more),true).
evidence(persons(more),true).
evidence(lug_boot(small),true).
evidence(safety(med),true).
query(car(_))
acc
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(more),true).
evidence(persons(more),true).
evidence(lug_boot(small),true).
evidence(safety(high),true).
query(car(_))
good
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(more),true).
evidence(persons(more),true).
evidence(lug_boot(med),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(more),true).
evidence(persons(more),true).
evidence(lug_boot(med),true).
evidence(safety(med),true).
query(car(_))
good
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(more),true).
evidence(persons(more),true).
evidence(lug_boot(med),true).
evidence(safety(high),true).
query(car(_))
vgood
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(more),true).
evidence(persons(more),true).
evidence(lug_boot(big),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(more),true).
evidence(persons(more),true).
evidence(lug_boot(big),true).
evidence(safety(med),true).
query(car(_))
good
-----
evidence(buying(low),true).
evidence(maint(med),true).
evidence(doors(more),true).
evidence(persons(more),true).
evidence(lug_boot(big),true).
evidence(safety(high),true).
query(car(_))
vgood
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(2),true).
evidence(persons(2),true).
evidence(lug_boot(small),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(2),true).
evidence(persons(2),true).
evidence(lug_boot(small),true).
evidence(safety(med),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(2),true).
evidence(persons(2),true).
evidence(lug_boot(small),true).
evidence(safety(high),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(2),true).
evidence(persons(2),true).
evidence(lug_boot(med),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(2),true).
evidence(persons(2),true).
evidence(lug_boot(med),true).
evidence(safety(med),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(2),true).
evidence(persons(2),true).
evidence(lug_boot(med),true).
evidence(safety(high),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(2),true).
evidence(persons(2),true).
evidence(lug_boot(big),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(2),true).
evidence(persons(2),true).
evidence(lug_boot(big),true).
evidence(safety(med),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(2),true).
evidence(persons(2),true).
evidence(lug_boot(big),true).
evidence(safety(high),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(2),true).
evidence(persons(4),true).
evidence(lug_boot(small),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(2),true).
evidence(persons(4),true).
evidence(lug_boot(small),true).
evidence(safety(med),true).
query(car(_))
acc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(2),true).
evidence(persons(4),true).
evidence(lug_boot(small),true).
evidence(safety(high),true).
query(car(_))
good
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(2),true).
evidence(persons(4),true).
evidence(lug_boot(med),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(2),true).
evidence(persons(4),true).
evidence(lug_boot(med),true).
evidence(safety(med),true).
query(car(_))
acc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(2),true).
evidence(persons(4),true).
evidence(lug_boot(med),true).
evidence(safety(high),true).
query(car(_))
good
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(2),true).
evidence(persons(4),true).
evidence(lug_boot(big),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(2),true).
evidence(persons(4),true).
evidence(lug_boot(big),true).
evidence(safety(med),true).
query(car(_))
good
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(2),true).
evidence(persons(4),true).
evidence(lug_boot(big),true).
evidence(safety(high),true).
query(car(_))
vgood
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(2),true).
evidence(persons(more),true).
evidence(lug_boot(small),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(2),true).
evidence(persons(more),true).
evidence(lug_boot(small),true).
evidence(safety(med),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(2),true).
evidence(persons(more),true).
evidence(lug_boot(small),true).
evidence(safety(high),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(2),true).
evidence(persons(more),true).
evidence(lug_boot(med),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(2),true).
evidence(persons(more),true).
evidence(lug_boot(med),true).
evidence(safety(med),true).
query(car(_))
acc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(2),true).
evidence(persons(more),true).
evidence(lug_boot(med),true).
evidence(safety(high),true).
query(car(_))
good
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(2),true).
evidence(persons(more),true).
evidence(lug_boot(big),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(2),true).
evidence(persons(more),true).
evidence(lug_boot(big),true).
evidence(safety(med),true).
query(car(_))
good
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(2),true).
evidence(persons(more),true).
evidence(lug_boot(big),true).
evidence(safety(high),true).
query(car(_))
vgood
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(3),true).
evidence(persons(2),true).
evidence(lug_boot(small),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(3),true).
evidence(persons(2),true).
evidence(lug_boot(small),true).
evidence(safety(med),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(3),true).
evidence(persons(2),true).
evidence(lug_boot(small),true).
evidence(safety(high),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(3),true).
evidence(persons(2),true).
evidence(lug_boot(med),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(3),true).
evidence(persons(2),true).
evidence(lug_boot(med),true).
evidence(safety(med),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(3),true).
evidence(persons(2),true).
evidence(lug_boot(med),true).
evidence(safety(high),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(3),true).
evidence(persons(2),true).
evidence(lug_boot(big),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(3),true).
evidence(persons(2),true).
evidence(lug_boot(big),true).
evidence(safety(med),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(3),true).
evidence(persons(2),true).
evidence(lug_boot(big),true).
evidence(safety(high),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(3),true).
evidence(persons(4),true).
evidence(lug_boot(small),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(3),true).
evidence(persons(4),true).
evidence(lug_boot(small),true).
evidence(safety(med),true).
query(car(_))
acc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(3),true).
evidence(persons(4),true).
evidence(lug_boot(small),true).
evidence(safety(high),true).
query(car(_))
good
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(3),true).
evidence(persons(4),true).
evidence(lug_boot(med),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(3),true).
evidence(persons(4),true).
evidence(lug_boot(med),true).
evidence(safety(med),true).
query(car(_))
acc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(3),true).
evidence(persons(4),true).
evidence(lug_boot(med),true).
evidence(safety(high),true).
query(car(_))
good
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(3),true).
evidence(persons(4),true).
evidence(lug_boot(big),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(3),true).
evidence(persons(4),true).
evidence(lug_boot(big),true).
evidence(safety(med),true).
query(car(_))
good
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(3),true).
evidence(persons(4),true).
evidence(lug_boot(big),true).
evidence(safety(high),true).
query(car(_))
vgood
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(3),true).
evidence(persons(more),true).
evidence(lug_boot(small),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(3),true).
evidence(persons(more),true).
evidence(lug_boot(small),true).
evidence(safety(med),true).
query(car(_))
acc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(3),true).
evidence(persons(more),true).
evidence(lug_boot(small),true).
evidence(safety(high),true).
query(car(_))
good
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(3),true).
evidence(persons(more),true).
evidence(lug_boot(med),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(3),true).
evidence(persons(more),true).
evidence(lug_boot(med),true).
evidence(safety(med),true).
query(car(_))
good
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(3),true).
evidence(persons(more),true).
evidence(lug_boot(med),true).
evidence(safety(high),true).
query(car(_))
vgood
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(3),true).
evidence(persons(more),true).
evidence(lug_boot(big),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(3),true).
evidence(persons(more),true).
evidence(lug_boot(big),true).
evidence(safety(med),true).
query(car(_))
good
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(3),true).
evidence(persons(more),true).
evidence(lug_boot(big),true).
evidence(safety(high),true).
query(car(_))
vgood
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(4),true).
evidence(persons(2),true).
evidence(lug_boot(small),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(4),true).
evidence(persons(2),true).
evidence(lug_boot(small),true).
evidence(safety(med),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(4),true).
evidence(persons(2),true).
evidence(lug_boot(small),true).
evidence(safety(high),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(4),true).
evidence(persons(2),true).
evidence(lug_boot(med),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(4),true).
evidence(persons(2),true).
evidence(lug_boot(med),true).
evidence(safety(med),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(4),true).
evidence(persons(2),true).
evidence(lug_boot(med),true).
evidence(safety(high),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(4),true).
evidence(persons(2),true).
evidence(lug_boot(big),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(4),true).
evidence(persons(2),true).
evidence(lug_boot(big),true).
evidence(safety(med),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(4),true).
evidence(persons(2),true).
evidence(lug_boot(big),true).
evidence(safety(high),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(4),true).
evidence(persons(4),true).
evidence(lug_boot(small),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(4),true).
evidence(persons(4),true).
evidence(lug_boot(small),true).
evidence(safety(med),true).
query(car(_))
acc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(4),true).
evidence(persons(4),true).
evidence(lug_boot(small),true).
evidence(safety(high),true).
query(car(_))
good
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(4),true).
evidence(persons(4),true).
evidence(lug_boot(med),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(4),true).
evidence(persons(4),true).
evidence(lug_boot(med),true).
evidence(safety(med),true).
query(car(_))
good
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(4),true).
evidence(persons(4),true).
evidence(lug_boot(med),true).
evidence(safety(high),true).
query(car(_))
vgood
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(4),true).
evidence(persons(4),true).
evidence(lug_boot(big),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(4),true).
evidence(persons(4),true).
evidence(lug_boot(big),true).
evidence(safety(med),true).
query(car(_))
good
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(4),true).
evidence(persons(4),true).
evidence(lug_boot(big),true).
evidence(safety(high),true).
query(car(_))
vgood
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(4),true).
evidence(persons(more),true).
evidence(lug_boot(small),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(4),true).
evidence(persons(more),true).
evidence(lug_boot(small),true).
evidence(safety(med),true).
query(car(_))
acc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(4),true).
evidence(persons(more),true).
evidence(lug_boot(small),true).
evidence(safety(high),true).
query(car(_))
good
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(4),true).
evidence(persons(more),true).
evidence(lug_boot(med),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(4),true).
evidence(persons(more),true).
evidence(lug_boot(med),true).
evidence(safety(med),true).
query(car(_))
good
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(4),true).
evidence(persons(more),true).
evidence(lug_boot(med),true).
evidence(safety(high),true).
query(car(_))
vgood
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(4),true).
evidence(persons(more),true).
evidence(lug_boot(big),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(4),true).
evidence(persons(more),true).
evidence(lug_boot(big),true).
evidence(safety(med),true).
query(car(_))
good
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(4),true).
evidence(persons(more),true).
evidence(lug_boot(big),true).
evidence(safety(high),true).
query(car(_))
vgood
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(more),true).
evidence(persons(2),true).
evidence(lug_boot(small),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(more),true).
evidence(persons(2),true).
evidence(lug_boot(small),true).
evidence(safety(med),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(more),true).
evidence(persons(2),true).
evidence(lug_boot(small),true).
evidence(safety(high),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(more),true).
evidence(persons(2),true).
evidence(lug_boot(med),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(more),true).
evidence(persons(2),true).
evidence(lug_boot(med),true).
evidence(safety(med),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(more),true).
evidence(persons(2),true).
evidence(lug_boot(med),true).
evidence(safety(high),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(more),true).
evidence(persons(2),true).
evidence(lug_boot(big),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(more),true).
evidence(persons(2),true).
evidence(lug_boot(big),true).
evidence(safety(med),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(more),true).
evidence(persons(2),true).
evidence(lug_boot(big),true).
evidence(safety(high),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(more),true).
evidence(persons(4),true).
evidence(lug_boot(small),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(more),true).
evidence(persons(4),true).
evidence(lug_boot(small),true).
evidence(safety(med),true).
query(car(_))
acc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(more),true).
evidence(persons(4),true).
evidence(lug_boot(small),true).
evidence(safety(high),true).
query(car(_))
good
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(more),true).
evidence(persons(4),true).
evidence(lug_boot(med),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(more),true).
evidence(persons(4),true).
evidence(lug_boot(med),true).
evidence(safety(med),true).
query(car(_))
good
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(more),true).
evidence(persons(4),true).
evidence(lug_boot(med),true).
evidence(safety(high),true).
query(car(_))
vgood
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(more),true).
evidence(persons(4),true).
evidence(lug_boot(big),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(more),true).
evidence(persons(4),true).
evidence(lug_boot(big),true).
evidence(safety(med),true).
query(car(_))
good
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(more),true).
evidence(persons(4),true).
evidence(lug_boot(big),true).
evidence(safety(high),true).
query(car(_))
vgood
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(more),true).
evidence(persons(more),true).
evidence(lug_boot(small),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(more),true).
evidence(persons(more),true).
evidence(lug_boot(small),true).
evidence(safety(med),true).
query(car(_))
acc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(more),true).
evidence(persons(more),true).
evidence(lug_boot(small),true).
evidence(safety(high),true).
query(car(_))
good
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(more),true).
evidence(persons(more),true).
evidence(lug_boot(med),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(more),true).
evidence(persons(more),true).
evidence(lug_boot(med),true).
evidence(safety(med),true).
query(car(_))
good
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(more),true).
evidence(persons(more),true).
evidence(lug_boot(med),true).
evidence(safety(high),true).
query(car(_))
vgood
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(more),true).
evidence(persons(more),true).
evidence(lug_boot(big),true).
evidence(safety(low),true).
query(car(_))
unacc
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(more),true).
evidence(persons(more),true).
evidence(lug_boot(big),true).
evidence(safety(med),true).
query(car(_))
good
-----
evidence(buying(low),true).
evidence(maint(low),true).
evidence(doors(more),true).
evidence(persons(more),true).
evidence(lug_boot(big),true).
evidence(safety(high),true).
query(car(_))
vgood
-----
