evidence(water,true).
evidence(adoption,false).
evidence(physician,false).
evidence(el,false).
evidence(religious,false).
evidence(anti,false).
evidence(aid,true).
evidence(mx,true).
evidence(immigration,false).
evidence(synfuels,true).
evidence(education,false).
evidence(superfund,false).
evidence(crime,false).
evidence(duty,true).
evidence(export,false).
query(party(democrat)).
-----
evidence(water,true).
evidence(adoption,false).
evidence(physician,true).
evidence(el,true).
evidence(religious,true).
evidence(anti,false).
evidence(aid,false).
evidence(mx,false).
evidence(immigration,false).
evidence(synfuels,true).
evidence(education,true).
evidence(superfund,true).
evidence(crime,true).
evidence(duty,false).
evidence(export,true).
query(party(republic)).
-----
evidence(el,false).
evidence(religious,true).
evidence(anti,false).
evidence(aid,true).
evidence(mx,true).
evidence(immigration,false).
evidence(synfuels,false).
evidence(education,true).
evidence(superfund,true).
evidence(crime,false).
evidence(duty,false).
query(party(republic)).
-----
evidence(water,true).
evidence(religious,true).
evidence(anti,false).
evidence(aid,false).
evidence(mx,false).
evidence(immigration,false).
evidence(synfuels,true).
evidence(education,false).
evidence(superfund,true).
evidence(crime,false).
evidence(duty,false).
evidence(export,true).
query(party(democrat)).
-----
evidence(water,true).
evidence(adoption,true).
evidence(el,false).
evidence(religious,false).
evidence(anti,false).
evidence(aid,true).
evidence(mx,false).
evidence(immigration,false).
evidence(synfuels,true).
evidence(superfund,false).
evidence(crime,false).
evidence(duty,true).
evidence(export,true).
query(party(democrat)).
-----
evidence(water,true).
evidence(adoption,true).
evidence(physician,false).
evidence(el,true).
evidence(religious,true).
evidence(anti,false).
evidence(aid,true).
evidence(mx,false).
evidence(immigration,false).
evidence(synfuels,true).
evidence(education,false).
evidence(superfund,true).
evidence(crime,false).
evidence(duty,true).
evidence(export,true).
query(party(democrat)).
-----
evidence(water,true).
evidence(adoption,false).
evidence(physician,false).
evidence(el,true).
evidence(anti,false).
evidence(aid,false).
evidence(mx,false).
evidence(immigration,false).
evidence(synfuels,true).
evidence(education,false).
evidence(superfund,true).
evidence(crime,true).
evidence(duty,false).
evidence(export,true).
query(party(democrat)).
-----
evidence(water,true).
evidence(adoption,true).
evidence(physician,false).
evidence(el,true).
evidence(religious,true).
evidence(anti,false).
evidence(aid,true).
evidence(mx,false).
evidence(immigration,false).
evidence(synfuels,false).
evidence(education,false).
evidence(superfund,false).
evidence(crime,false).
evidence(duty,false).
evidence(export,true).
query(party(democrat)).
-----
evidence(water,true).
evidence(adoption,false).
evidence(physician,true).
evidence(religious,true).
evidence(anti,false).
evidence(aid,false).
evidence(mx,false).
evidence(immigration,true).
evidence(synfuels,false).
evidence(education,true).
evidence(superfund,true).
evidence(crime,true).
evidence(duty,false).
evidence(export,false).
query(party(republic)).
-----
evidence(water,true).
evidence(adoption,false).
evidence(physician,true).
evidence(el,true).
evidence(religious,true).
evidence(anti,false).
evidence(mx,false).
evidence(immigration,false).
evidence(crime,true).
evidence(duty,false).
query(party(republic)).
-----
evidence(water,true).
evidence(adoption,false).
evidence(physician,true).
evidence(el,true).
evidence(religious,true).
evidence(anti,false).
evidence(aid,false).
evidence(mx,false).
evidence(immigration,true).
evidence(synfuels,true).
evidence(education,true).
evidence(superfund,true).
evidence(crime,true).
evidence(duty,false).
evidence(export,false).
query(party(republic)).
-----
evidence(water,false).
evidence(adoption,true).
evidence(physician,true).
evidence(el,false).
evidence(religious,true).
evidence(anti,true).
evidence(aid,true).
evidence(mx,true).
evidence(immigration,true).
evidence(synfuels,false).
evidence(education,true).
evidence(superfund,false).
evidence(crime,true).
evidence(duty,false).
evidence(export,true).
query(party(republic)).
-----
evidence(water,true).
evidence(adoption,false).
evidence(physician,true).
evidence(el,true).
evidence(religious,true).
evidence(anti,false).
evidence(aid,false).
evidence(mx,false).
evidence(immigration,true).
evidence(synfuels,false).
evidence(education,true).
evidence(crime,true).
evidence(duty,false).
evidence(export,false).
query(party(republic)).
-----
evidence(water,true).
evidence(adoption,false).
evidence(physician,true).
evidence(el,true).
evidence(religious,true).
evidence(anti,false).
evidence(aid,false).
evidence(mx,false).
evidence(immigration,true).
evidence(synfuels,false).
evidence(education,true).
evidence(superfund,true).
evidence(crime,true).
evidence(duty,false).
evidence(export,true).
query(party(republic)).
-----
evidence(water,false).
evidence(adoption,false).
evidence(physician,true).
evidence(el,true).
evidence(religious,true).
evidence(anti,false).
evidence(aid,false).
evidence(mx,false).
evidence(immigration,false).
evidence(synfuels,false).
evidence(education,true).
evidence(superfund,true).
evidence(crime,true).
evidence(duty,false).
evidence(export,true).
query(party(republic)).
-----
evidence(water,false).
evidence(adoption,true).
evidence(physician,false).
evidence(el,true).
evidence(religious,true).
evidence(anti,false).
evidence(aid,false).
evidence(mx,true).
evidence(immigration,true).
evidence(synfuels,false).
evidence(education,false).
evidence(superfund,true).
evidence(crime,true).
evidence(duty,false).
evidence(export,true).
query(party(democrat)).
-----
evidence(water,false).
evidence(adoption,false).
evidence(physician,true).
evidence(el,true).
evidence(religious,true).
evidence(anti,false).
evidence(aid,false).
evidence(mx,false).
evidence(immigration,false).
evidence(synfuels,true).
evidence(education,true).
evidence(superfund,true).
evidence(crime,true).
evidence(duty,false).
evidence(export,false).
query(party(democrat)).
-----
evidence(water,false).
evidence(adoption,true).
evidence(physician,false).
evidence(el,false).
evidence(religious,true).
evidence(anti,true).
evidence(aid,true).
evidence(mx,true).
evidence(immigration,false).
evidence(synfuels,false).
evidence(education,true).
evidence(crime,true).
evidence(duty,true).
evidence(export,true).
query(party(democrat)).
-----
evidence(water,false).
evidence(adoption,false).
evidence(physician,true).
evidence(el,true).
evidence(religious,true).
evidence(anti,false).
evidence(aid,false).
evidence(mx,false).
evidence(immigration,false).
evidence(synfuels,false).
evidence(education,true).
evidence(superfund,true).
evidence(crime,true).
evidence(duty,false).
evidence(export,false).
query(party(republic)).
-----
evidence(water,false).
evidence(adoption,false).
evidence(physician,true).
evidence(el,true).
evidence(religious,true).
evidence(anti,false).
evidence(aid,false).
evidence(mx,false).
evidence(immigration,false).
evidence(synfuels,true).
evidence(education,true).
evidence(superfund,true).
evidence(crime,true).
evidence(duty,false).
evidence(export,true).
query(party(republic)).
-----
evidence(water,false).
evidence(adoption,true).
evidence(physician,false).
evidence(el,false).
evidence(religious,true).
evidence(anti,true).
evidence(aid,true).
evidence(mx,true).
evidence(immigration,true).
evidence(synfuels,true).
evidence(education,false).
evidence(superfund,false).
evidence(crime,false).
evidence(duty,false).
evidence(export,true).
query(party(democrat)).
-----
evidence(water,false).
evidence(adoption,false).
evidence(physician,true).
evidence(el,true).
evidence(religious,true).
evidence(anti,false).
evidence(aid,false).
evidence(mx,false).
evidence(immigration,true).
evidence(synfuels,false).
evidence(education,true).
evidence(superfund,true).
evidence(crime,true).
evidence(duty,false).
evidence(export,true).
query(party(republic)).
-----
evidence(water,true).
evidence(adoption,true).
evidence(physician,true).
evidence(el,true).
evidence(religious,true).
evidence(anti,true).
evidence(aid,true).
evidence(mx,false).
evidence(immigration,true).
evidence(crime,true).
evidence(duty,false).
evidence(export,true).
query(party(republic)).
-----
evidence(water,true).
evidence(adoption,true).
evidence(physician,false).
evidence(el,false).
evidence(religious,false).
evidence(anti,true).
evidence(aid,true).
evidence(mx,true).
evidence(immigration,false).
evidence(synfuels,false).
evidence(education,false).
evidence(superfund,false).
evidence(crime,false).
evidence(duty,false).
evidence(export,true).
query(party(democrat)).
-----
evidence(water,true).
evidence(adoption,true).
evidence(physician,false).
evidence(el,false).
evidence(religious,true).
evidence(anti,true).
evidence(aid,true).
evidence(immigration,true).
evidence(synfuels,false).
evidence(education,false).
evidence(superfund,false).
evidence(crime,false).
evidence(duty,false).
evidence(export,true).
query(party(democrat)).
-----
evidence(water,true).
evidence(adoption,false).
evidence(physician,true).
evidence(el,true).
evidence(religious,true).
evidence(anti,false).
evidence(aid,false).
evidence(mx,false).
evidence(immigration,true).
evidence(synfuels,false).
evidence(education,false).
evidence(superfund,true).
evidence(crime,true).
evidence(duty,false).
evidence(export,true).
query(party(republic)).
-----
evidence(water,true).
evidence(adoption,true).
evidence(physician,false).
evidence(el,false).
evidence(religious,false).
evidence(anti,true).
evidence(aid,true).
evidence(mx,true).
evidence(immigration,true).
evidence(synfuels,true).
evidence(education,false).
evidence(superfund,true).
evidence(crime,false).
evidence(duty,false).
evidence(export,true).
query(party(democrat)).
-----
evidence(water,true).
evidence(adoption,true).
evidence(physician,false).
evidence(el,false).
evidence(religious,false).
evidence(anti,true).
evidence(aid,true).
evidence(mx,false).
evidence(immigration,true).
evidence(synfuels,false).
evidence(education,false).
evidence(superfund,false).
evidence(crime,false).
evidence(duty,false).
evidence(export,true).
query(party(democrat)).
-----
evidence(water,true).
evidence(adoption,true).
evidence(physician,false).
evidence(el,false).
evidence(religious,false).
evidence(anti,true).
evidence(aid,true).
evidence(mx,true).
evidence(immigration,false).
evidence(synfuels,false).
evidence(education,false).
evidence(superfund,false).
evidence(crime,false).
evidence(duty,false).
evidence(export,true).
query(party(democrat)).
-----
evidence(water,true).
evidence(adoption,true).
evidence(physician,true).
evidence(el,true).
evidence(religious,true).
evidence(anti,true).
evidence(aid,true).
evidence(mx,false).
evidence(immigration,true).
evidence(synfuels,false).
evidence(education,false).
evidence(superfund,true).
evidence(crime,true).
evidence(duty,false).
evidence(export,true).
query(party(republic)).
-----
evidence(water,true).
evidence(adoption,true).
evidence(physician,false).
evidence(el,true).
evidence(religious,true).
evidence(anti,true).
evidence(aid,true).
evidence(mx,false).
evidence(immigration,false).
evidence(synfuels,true).
evidence(education,false).
evidence(superfund,true).
evidence(crime,false).
evidence(duty,true).
evidence(export,true).
query(party(democrat)).
-----
evidence(water,false).
evidence(adoption,true).
evidence(physician,false).
evidence(el,false).
evidence(religious,true).
evidence(anti,true).
evidence(aid,true).
evidence(mx,true).
evidence(immigration,false).
evidence(synfuels,true).
evidence(education,false).
evidence(superfund,false).
evidence(crime,false).
evidence(duty,true).
evidence(export,true).
query(party(democrat)).
-----
evidence(water,true).
evidence(adoption,true).
evidence(physician,false).
evidence(el,false).
evidence(religious,true).
evidence(anti,true).
evidence(aid,true).
evidence(mx,true).
evidence(immigration,false).
evidence(synfuels,true).
evidence(education,false).
evidence(superfund,false).
evidence(crime,true).
evidence(duty,true).
evidence(export,true).
query(party(democrat)).
-----
evidence(water,true).
evidence(adoption,true).
evidence(physician,false).
evidence(el,false).
evidence(anti,true).
evidence(aid,true).
evidence(mx,true).
evidence(immigration,true).
evidence(synfuels,true).
evidence(education,false).
evidence(crime,true).
evidence(duty,true).
evidence(export,true).
query(party(democrat)).
-----
evidence(water,false).
evidence(adoption,true).
evidence(physician,false).
evidence(el,false).
evidence(religious,false).
evidence(anti,true).
evidence(aid,true).
evidence(mx,false).
evidence(immigration,true).
evidence(synfuels,true).
evidence(education,false).
evidence(superfund,false).
evidence(crime,false).
evidence(duty,true).
query(party(democrat)).
-----
evidence(water,false).
evidence(adoption,true).
evidence(physician,false).
evidence(el,false).
evidence(religious,false).
evidence(anti,true).
evidence(aid,true).
evidence(mx,true).
evidence(immigration,true).
evidence(synfuels,false).
evidence(education,false).
evidence(superfund,false).
evidence(crime,false).
evidence(duty,true).
evidence(export,true).
query(party(democrat)).
-----
evidence(water,false).
evidence(adoption,false).
evidence(physician,true).
evidence(el,true).
evidence(religious,true).
evidence(anti,true).
evidence(aid,true).
evidence(mx,false).
evidence(immigration,true).
evidence(synfuels,false).
evidence(education,true).
evidence(superfund,true).
evidence(crime,true).
evidence(duty,false).
evidence(export,true).
query(party(republic)).
-----
evidence(physician,false).
evidence(el,false).
evidence(religious,false).
evidence(anti,true).
evidence(aid,true).
evidence(mx,true).
evidence(immigration,true).
evidence(synfuels,false).
evidence(education,false).
evidence(superfund,true).
evidence(crime,false).
evidence(duty,true).
evidence(export,true).
query(party(democrat)).
-----
evidence(water,false).
evidence(adoption,true).
evidence(physician,false).
evidence(religious,false).
evidence(anti,true).
evidence(aid,true).
evidence(mx,true).
evidence(immigration,true).
evidence(synfuels,false).
evidence(education,true).
evidence(superfund,false).
evidence(duty,true).
evidence(export,true).
query(party(democrat)).
-----
evidence(water,false).
evidence(adoption,true).
evidence(physician,true).
evidence(el,true).
evidence(religious,true).
evidence(anti,false).
evidence(aid,false).
evidence(mx,true).
evidence(immigration,true).
evidence(synfuels,false).
evidence(education,true).
evidence(superfund,true).
evidence(crime,true).
evidence(duty,false).
evidence(export,true).
query(party(republic)).
-----
evidence(water,false).
evidence(adoption,true).
evidence(physician,false).
evidence(el,false).
evidence(religious,false).
evidence(anti,true).
evidence(aid,true).
evidence(mx,true).
evidence(immigration,true).
evidence(synfuels,false).
evidence(education,false).
evidence(superfund,false).
evidence(crime,false).
evidence(duty,false).
evidence(export,true).
query(party(democrat)).
-----
evidence(adoption,false).
evidence(physician,true).
evidence(el,true).
evidence(religious,true).
evidence(anti,false).
evidence(aid,false).
evidence(mx,false).
evidence(immigration,false).
evidence(synfuels,true).
evidence(education,true).
evidence(superfund,true).
evidence(crime,true).
evidence(duty,false).
evidence(export,true).
query(party(republic)).
-----
evidence(water,false).
evidence(adoption,false).
evidence(physician,true).
evidence(el,true).
evidence(religious,true).
evidence(synfuels,false).
evidence(education,true).
evidence(superfund,true).
evidence(crime,true).
evidence(duty,false).
evidence(export,true).
query(party(republic)).
-----
evidence(water,true).
evidence(adoption,false).
evidence(physician,true).
evidence(el,true).
evidence(religious,true).
evidence(anti,false).
evidence(aid,false).
evidence(mx,false).
evidence(immigration,true).
evidence(synfuels,false).
evidence(education,true).
evidence(superfund,true).
evidence(crime,true).
evidence(export,false).
query(party(republic)).
-----
